# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f15b0fe282bd9e15bc77123eb69b7228e96b5c2f495fc1fcc0bdebc3238a8c22001f2f8d5e93430b0e8f6042552fa6ec0add1fe2d9d1cef7b5b8e480dc551118

test:
  secret_key_base: c53742ccbd293105efb00d836b747ca78f620d35da5dfaa508c5450da740174f42e42449a216a6627d22f20cd2adf77ee7f86ad3ab2b29e167cf454db9b91808

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
